import React from 'react';
import { Memori, Message, Tenant, Venue, User } from '@memori.ai/memori-api-client/dist/types';
import memoriApiClient from '@memori.ai/memori-api-client';
import { Props as WidgetProps } from '../MemoriWidget/MemoriWidget';
export interface Props {
    className?: string;
    memori: Memori;
    tenant?: Tenant;
    history: Message[];
    position?: Venue;
    setShowPositionDrawer: (show: boolean) => void;
    setShowSettingsDrawer: (show: boolean) => void;
    setShowChatHistoryDrawer: (show: boolean) => void;
    setShowKnownFactsDrawer: (show: boolean) => void;
    setShowExpertsDrawer: (show: boolean) => void;
    enableAudio?: boolean;
    speakerMuted: boolean;
    setSpeakerMuted: (mute: boolean) => void;
    hasUserActivatedSpeak?: boolean;
    showShare?: boolean;
    showSettings?: boolean;
    showChatHistory?: boolean;
    showReload?: boolean;
    showClear?: boolean;
    showLogin?: boolean;
    setShowLoginDrawer: (show: boolean) => void;
    clearHistory: () => void;
    loginToken?: string;
    user?: User;
    sessionID?: string;
    baseUrl?: string;
    fullScreenHandler?: (e: React.MouseEvent<HTMLButtonElement>) => void;
    onLogout?: () => void;
    apiClient: ReturnType<typeof memoriApiClient>;
    layout?: WidgetProps['layout'];
    additionalSettings?: WidgetProps['additionalSettings'];
    showMessageConsumption?: boolean;
}
declare const Header: React.FC<Props>;
export default Header;
