import React from 'react';
import { render } from '@testing-library/react';
import ChatBubble from './ChatBubble';
import { memori, tenant } from '../../mocks/data';

it('renders ChatBubble unchanged', () => {
  const { container } = render(
    <ChatBubble
      memori={memori}
      tenant={tenant}
      message={{
        fromUser: false,
        text: 'Proin libero ante, dignissim sit amet turpis a, pretium condimentum dolor.',
        initial: false,
        translatedText:
          'Proin libero ante, dignissim sit amet turpis a, pretium condimentum dolor.',
      }}
    />
  );
  expect(container).toMatchSnapshot();
});

it('renders ChatBubble with initial msg unchanged', () => {
  const { container } = render(
    <ChatBubble
      memori={memori}
      tenant={tenant}
      message={{
        fromUser: false,
        text: 'Proin libero ante, dignissim sit amet turpis a, pretium condimentum dolor.',
        initial: true,
        translatedText:
          'Proin libero ante, dignissim sit amet turpis a, pretium condimentum dolor.',
      }}
    />
  );
  expect(container).toMatchSnapshot();
});

it('renders ChatBubble with user msg unchanged', () => {
  const { container } = render(
    <ChatBubble
      memori={memori}
      tenant={tenant}
      message={{
        fromUser: true,
        text: 'Proin libero ante, dignissim sit amet turpis a, pretium condimentum dolor.',
        initial: false,
        translatedText:
          'Proin libero ante, dignissim sit amet turpis a, pretium condimentum dolor.',
      }}
    />
  );
  expect(container).toMatchSnapshot();
});

it('renders ChatBubble with msg generated by AI unchanged', () => {
  const { container } = render(
    <ChatBubble
      memori={memori}
      tenant={tenant}
      message={{
        fromUser: true,
        text: 'Proin libero ante, dignissim sit amet turpis a, pretium condimentum dolor.',
        initial: false,
        generatedByAI: true,
        translatedText:
          'Proin libero ante, dignissim sit amet turpis a, pretium condimentum dolor.',
      }}
    />
  );
  expect(container).toMatchSnapshot();
});

it('renders ChatBubble with msg from BoE expert unchanged', () => {
  const { container } = render(
    <ChatBubble
      memori={{
        ...memori,
        enableBoardOfExperts: true,
      }}
      tenant={tenant}
      apiUrl="https://backend.memori.ai"
      experts={[
        {
          expertID: '9b0a2913-d3d8-4e98-a49d-6e1c99479e1b',
          name: 'Expert name',
          description: 'Expert description',
          expertMemoriID: '9b0a2913-d3d8-4e98-a49d-6e1c99479e1b',
          expertBaseURL: 'https://engine.memori.ai',
        },
      ]}
      message={{
        fromUser: true,
        text: 'Proin libero ante, dignissim sit amet turpis a, pretium condimentum dolor.',
        initial: false,
        generatedByAI: true,
        emitter: 'Expert name',
        translatedText:
          'Proin libero ante, dignissim sit amet turpis a, pretium condimentum dolor.',
      }}
    />
  );
  expect(container).toMatchSnapshot();
});

it('renders ChatBubble from user with avatar unchanged', () => {
  const { container } = render(
    <ChatBubble
      memori={memori}
      tenant={tenant}
      user={{ avatarURL: 'https://picsum.photos/200' }}
      message={{
        fromUser: true,
        text: 'Proin libero ante, dignissim sit amet turpis a, pretium condimentum dolor.',
        initial: false,
        translatedText:
          'Proin libero ante, dignissim sit amet turpis a, pretium condimentum dolor.',
      }}
    />
  );
  expect(container).toMatchSnapshot();
});

it('renders ChatBubble from user with custom avatar unchanged', () => {
  const { container } = render(
    <ChatBubble
      memori={memori}
      tenant={tenant}
      userAvatar="https://picsum.photos/200"
      message={{
        fromUser: true,
        text: 'Proin libero ante, dignissim sit amet turpis a, pretium condimentum dolor.',
        initial: false,
        translatedText:
          'Proin libero ante, dignissim sit amet turpis a, pretium condimentum dolor.',
      }}
    />
  );
  expect(container).toMatchSnapshot();
});

it('renders ChatBubble from user with avatar as react element unchanged', () => {
  const { container } = render(
    <ChatBubble
      memori={memori}
      tenant={tenant}
      user={{ avatarURL: 'https://picsum.photos/200' }}
      userAvatar={<span>USER</span>}
      message={{
        fromUser: true,
        text: 'Proin libero ante, dignissim sit amet turpis a, pretium condimentum dolor.',
        initial: false,
        translatedText:
          'Proin libero ante, dignissim sit amet turpis a, pretium condimentum dolor.',
      }}
    />
  );
  expect(container).toMatchSnapshot();
});
