name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['22.x', '24.x']
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: ⚒ Install deps
        run: corepack enable && yarn install --immutable

      - name: 🔎 Lint
        run: yarn lint

      - name: 🧪 Test
        run: yarn test:ci --coverage --maxWorkers=2

      - name: ⚙️ Build
        run: yarn build

      - name: 🚨 Audit
        run: yarn npm audit --environment production
